[versions]
agp = "8.13.0"
kotlin = "2.2.21"
coreKtx = "1.15.0"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.1.0"
material = "1.10.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
constraintlayout = 'androidx.constraintlayout:constraintlayout:1.1.3'
kotlin-stdlib8 = "org.jetbrains.kotlin:kotlin-stdlib-jdk8:2.2.0"
kotlin-coroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.1"
kotlin-coroutines-android = "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.6.1"
viewmodel = 'androidx.lifecycle:lifecycle-viewmodel:2.2.0'
viewmodel-ktx = 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.2.0'
recyclerview = 'androidx.recyclerview:recyclerview:1.2.1'

logger = 'io.github.ayvytr:logger:+'
flow = 'io.github.ayvytr:flow:+'
network = 'io.github.ayvytr:network:+'

leakcanary = 'com.squareup.leakcanary:leakcanary-android:+'
crashreport = 'com.tencent.bugly:crashreport:+'

base-adapter = 'io.github.ayvytr:base-adapter:+'
ktx-androidx = 'io.github.ayvytr:ktx-androidx:+'

scwang90-refresh-kernel=  'io.github.scwang90:refresh-layout-kernel:2.0.5'
scwang90-refresh-header-classics = 'io.github.scwang90:refresh-header-classics:2.0.5'

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
